# Generated by Django 3.0.2 on 2020-01-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200103_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_posted',
        ),
    ]
