# Generated by Django 3.0.2 on 2020-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_document_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_posted',
            field=models.CharField(default='03 January 2020 10:41AM', max_length=70),
        ),
    ]
