# Generated by Django 3.0.2 on 2020-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='about',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_posted',
            field=models.CharField(default='03 January 2020 02:35PM', max_length=70),
        ),
    ]
